using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.DAL;

namespace WebApplication1.Controllers
{
    [HandleError]
    public class HomeController : Controller
    {
        crewjail2017_dbEntities _db; //an instance of the test class that was generated by the Entity Designer
        public HomeController()
        {
            _db = new crewjail2017_dbEntities();
        }
        public ActionResult Index()
        {
            ViewData.Model = _db.Tests.ToList();
            return View();
                
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Calendar()
        {
            return View();
        }
    }
}